batch_size: 4096
epochs: 100
eval_every_n_epochs: 1
fine_tune_from: ''
log_every_n_steps: 25
weight_decay: 10e-6
fp16_precision: False
n_gpu: 1
gpu_ids: (0, 1)

model:
  out_dim: 256
  base_model: "resnet18"

dataset:
  s: 1
  input_shape: (256,256,3)
  num_workers: 6
  valid_size: 0.1

loss:
  temperature: 0.5
  use_cosine_similarity: True
